export interface Registration {
    id?:number,
	fullName?:string,
    address?:string,
    zipCode?:string,
    state?:string,
    country?:string,
    birthDate?:Date,
    document?:string,
    phone?:string,
    email?:string,
    salary?:number,
    createdAt?:Date,
    decision?:string,
    bankCode?:number,
}